groups:
- name: all
  jobs:
  - plctest

## ======================================================================
## resource types
## ======================================================================

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource



resources:
- name: plc_src
  type: git
  source:
    branch: pipeline
    uri: https://github.com/greenplum-db/plcontainer.git
- name: ccp_src
  type: git
  source:
    branch: {{ccp-git-branch}}
    private_key: {{ccp-git-key}}
    uri: {{ccp-git-remote}}
- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}
    ignore_paths:
    - gpdb-doc/*
    - README*
- name: terraform
  type: terraform
  source:
    env:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
    storage:
      access_key_id: {{tf-machine-access-key-id}}
      secret_access_key: {{tf-machine-secret-access-key}}
      region_name: {{aws-region}}
      # This is not parameterized, on purpose. All tfstates will go to this spot,
      # and different teams will place there clusters' tfstate files under different paths
      bucket: gpdb5-pipeline-dynamic-terraform
      ###########################################################
      # Two conventions are allowed for bucket_path:            #
      # 1) Cluster are expected to be destroyed automatically   #
      #    Toolsmiths will reap old and orphaned clusters       #
      #                                                         #
      #      bucket_path: prod/[Pipeline Name]/                 #
      #                                                         #
      # 2) Long lived clusters for development.                 #
      #    The team that creates it is responsible for cluster  #
      #                                                         #
      #     bucket_path: dev/[Team Name]/                       #
      #                                                         #
      ###########################################################
      bucket_path: {{tf-bucket-path}}




- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: 6-gcc6.2-llvm3.7

- name: bin_gpdb_centos6
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: {{bin_gpdb_centos_versioned_file}}

jobs:
- name: plctest
  plan:
  - aggregate:
    - get: plc_src
    - get: gpdb_src
    - get: gpdb_binary
      resource: bin_gpdb_centos6
    - get: ccp_src
    - get: centos-gpdb-dev-6
  - put: terraform
    params:
      action: create
      delete_on_failure: true
      generate_random_name: true
      terraform_source: ccp_src/aws/
      vars:
        aws_instance-node-instance_type: t2.medium
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    on_failure:
      put: terraform
      params:
        action: destroy
        env_name_file: terraform/name
        terraform_source: ccp_src/aws/
        vars:
          aws_instance-node-instance_type: t2.micro
      get_params:
        action: destroy
  - task: plcontainer
    file: plc_src/concourse/tasks/plcontainer.yml
    image: centos-gpdb-dev-6
